- hosts: localhost
  roles:
     - {role: digitransit-azure-appgw}
  vars:
     environment_type: PROD
     project_name: peatusee
     project: peatusee
     certfile: /home/jz/digitransit-mesos-deploy/self_signed_ssl/test.pfx
     certpass: fM2hkebDfcPq
     backend_servers: "peatusee-prod-acsagents.westeurope.cloudapp.azure.com"
